{% set name = "dspawpy" %}
{% set version = "1.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 598cb07faaca319d55d8d6219246591318edabb9309928c0e70ea94afa9a75af

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py >=3.7
    - pymatgen >=2021.2.8.1
    - python >=3.6
    - statsmodels >=0.12.0
    - prompt_toolkit
    - loguru

test:
  imports:
    - dspawpy
    - dspawpy.analysis
    - dspawpy.diffusion
    - dspawpy.io

about:
  home: "http://www.hzwtech.com/"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Tools for dspaw"
  doc_url: http://hzwtech.com/Device%20Studio/DS-PAW/build/html/tools.html
  dev_url: http://hzwtech.com/Device%20Studio/DS-PAW/build/htmldspawpy/latest/dspawpy.html

extra:
  recipe-maintainers:
    - bernt-matthias
    - m3lab-zzl
